# Generated by Django 3.0.3 on 2020-03-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=121)),
                ('description', models.TextField()),
                ('published', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title', 'published', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=121)),
                ('posts', models.ManyToManyField(to='mysite.Post')),
            ],
            options={
                'ordering': ['topic_name'],
            },
        ),
    ]
