# Generated by Django 3.0.3 on 2020-03-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200324_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ManyToManyField(to='mysite.Topic'),
        ),
    ]
