# Generated by Django 3.0.3 on 2020-03-24 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200324_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Post')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Topic')),
            ],
        ),
    ]
