# Generated by Django 3.0.3 on 2020-03-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_categorypost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=121, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=121, unique=True),
        ),
        migrations.DeleteModel(
            name='CategoryPost',
        ),
    ]
