# Generated by Django 3.0.3 on 2020-03-25 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mysite', '0006_auto_20200325_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=121, unique=True)),
                ('content', models.TextField()),
                ('published', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_name', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('posts', models.ManyToManyField(to='mysite.Post')),
            ],
        ),
    ]
