# Generated by Django 3.0 on 2020-03-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='introduce',
            field=models.CharField(default='Introduce post', max_length=300),
        ),
    ]
