# Generated by Django 3.0 on 2020-03-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_post_introduce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(to='mysite.Topic'),
        ),
    ]
