# Generated by Django 3.0 on 2020-04-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20200331_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kind_post',
            field=models.CharField(choices=[('BT', 'Bình thường'), ('BH', 'Bài hay'), ('NM', 'Nhập môn')], default='BT', max_length=2),
        ),
    ]
